spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/articles
    username: postgres
    password: bassmeister
    initialization-mode: always
  liquibase:
    url: jdbc:postgresql://localhost:5433/articles
    user: postgres
    password: bassmeister
    changelog: classpath:db/changelog/master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    io.r2dbc.postgresql.QUERY: INFO # for queries